version: ">= 0.13.0"

formatter: markdown

header-from: main.tf
footer-from: ""

sections:
  hide: []
  show:
  - requirements
  - inputs
  - outputs
  - resources

content: |-
  # AWS ALB Module

  This module to create AWS ALB form a set of list

  {{ .Requirements }}

  ## Examples

  ```hcl
  {{ include "examples/main.tf" }}
  ```

  {{ .Inputs }}
  
  {{ .Outputs }}

  {{ .Resources }}

  ## Authors

  Created by [M.Farhan Taib](https://github.com/ftcodelib) - https://my.linkedin.com/in/mohdfarhantaib.

  ## License

  Apache License 2.0 Licensed. See [LICENSE](LICENSE) for full details.

output:
  file: README.md
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->    

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  html: true
  indent: 2
  required: true
  sensitive: true
  type: true